<a href="https://colab.research.google.com/github/mehjabeenalam-ux/REC-2-Machine-Learning/blob/main/Class_02_Exercises_DIP_mehjabeen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is a module or library in Python that deals with fast computation on arrays.

1. Create 1D and 2D arrays
- Create a 1D NumPy array from the Python list [2, 4, 6, 8].
- Create a 2D NumPy array with 2 rows and 3 columns using any numbers you want.

In [41]:
import numpy as np

array_1D = np.array([2,4,6,8])
array_2D = [
          [1,2,3],
          [4,5,6]

]

print(array_1D)
print(type(array_1D))
print(array_2D)
print(type(array_2D))

[2 4 6 8]
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6]]
<class 'list'>


2. Check basic properties
Given:
X = np.array([[1, 2, 3],
[4, 5, 6]])
- Print X.shape
- Print X.ndim
- Print X.dtype

In [7]:
X = np.array([[1, 2, 3], [4, 5, 6]])
print(X.shape)
print(X.ndim)
print(X.dtype)

(2, 3)
2
int64


3. Zeros and ones
- Create a 3×3 array filled with zeros.
- Create a 2×4 array filled with ones.

In [16]:
#Zeroes
zeroes = np.zeros((3,3))
# print(np.zeros((3,3)))
print(zeroes)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
##Ones
ones = np.ones((2,4))
# print(np.ones((2,4)))
print(ones)

4. arange vs linspace
- Use np.arange to create an array: [0, 2, 4, 6, 8].
- Use np.linspace to create 5 values from 0 to 1 (inclusive).

In [14]:
#np.arrange
array_arange = np.arange(0,9,2)
print(array_arange)

[0 2 4 6 8]


In [15]:
#np.linspace
array_linspace = np.linspace(0, 1, 5)
print(array_linspace)

[0.   0.25 0.5  0.75 1.  ]


5. Indexing single elements
Given:
X = np.array([[800, 2, 15],
[950, 2, 10],
[1200, 3, 8],
[1500, 3, 5]])
- Get the first element (800)
- Get the value 3 (bedrooms of the 3rd row)
- Get the last element (5)

New Array

In [27]:
x_new = np.array([[800, 2, 15],
                  [950, 2, 10],
                  [1200, 3, 8],
                  [1500, 3, 5]]
                 )
print(x_new)

[[ 800    2   15]
 [ 950    2   10]
 [1200    3    8]
 [1500    3    5]]


Get the first element (800)

In [33]:
# print(x[0])
print(x_new[0,0])

800


Get the value 3 (bedrooms of the 3rd row)

In [34]:
print(x_new[2])

[1200    3    8]


Get the last element (5)

In [35]:
print(x_new[3,2])

5


6. Row and column selection
Using the same X as above:
- Get the first row as an array.
- Get the second column (all bedroom values).

Get the first row as an array.

In [42]:
#Get the first row as an array.
print(np.array(x_new[0]))
print(type(np.array(x_new[0])))

[800   2  15]
<class 'numpy.ndarray'>


Get the second column (all bedroom values).

In [65]:
print(np.array(x_new[:,1]))

[2 2 3 3]


7. Slicing rows and columns
From the same X:
- Get the first 2 rows.
- Get rows 1 to 3 and columns 0 to 1.


In [62]:
#Get the first 2 rows.
print(np.array(x_new[0:2]))

[[800   2  15]
 [950   2  10]]


In [63]:
#Get rows 1 to 3 and columns 0 to 1.
print(np.array(x_new[1:4,0:2]))

[[ 950    2]
 [1200    3]
 [1500    3]]


8. Feature/target split
Consider:
data = np.array([
[800, 2, 15, 75000],
[950, 2, 10, 90000],
[1200, 3, 8, 120000],
[1500, 3, 5, 155000]
])
- Use slicing to create X (first 3 columns) and y (last column)

In [72]:
data = np.array([
[800, 2, 15, 75000],
[950, 2, 10, 90000],
[1200, 3, 8, 120000],
[1500, 3, 5, 155000]
])
print(type(data))
print(np.array(data[:,0:3]))
print(np.array(data[:,3]))

<class 'numpy.ndarray'>
[[ 800    2   15]
 [ 950    2   10]
 [1200    3    8]
 [1500    3    5]]
[ 75000  90000 120000 155000]


9. Mean and standard deviation
Using the same data array:
- Compute the overall mean of all numbers.
- Compute the standard deviation of all numbers.


In [35]:
data = np.array([
[800, 2, 15, 75000],
[950, 2, 10, 90000],
[1200, 3, 8, 120000],
[1500, 3, 5, 155000]
])

print(data)
print(type(data))

#Mean
print(np.mean(data))
print(f"Mean of this array is {np.mean(data)}")


#StandardDeviation
print(data.std)
print(f"Standard Deviation of this array is {data.std()}")

[[   800      2     15  75000]
 [   950      2     10  90000]
 [  1200      3      8 120000]
 [  1500      3      5 155000]]
<class 'numpy.ndarray'>
27781.125
Mean of this array is 27781.125
<built-in method std of numpy.ndarray object at 0x7de46d20eb50>
Standard Deviation of this array is 49878.965030204614


10. Mean per column
For data above:
- Compute the mean of each column using axis=0.
- What does the mean of the last column represent?


In [38]:
col_means = data.mean(axis=0)




11. Min and max per feature
For data above:
- Compute the minimum of each feature column (first 3 columns).
- Compute the maximum of each feature column (first 3 columns).

12. Reshape and flatten
- Create a = np.array([1, 2, 3, 4, 5, 6]).
- Reshape it into a 2×3 matrix.
- Then flatten it back to 1D.


In [12]:
#Reshape into a 2X3 Matrix

import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
reshape = a.reshape(2,3)
print(reshape)

#Flatten into a 1D Array

flat = reshape.flatten()
print(flat)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


13. Vertical and horizontal stacking
Given:
A = np.array([[1, 2],
[3, 4]])
B = np.array([[5, 6],
[7, 8]])
- Use np.vstack to stack them vertically.
- Use np.hstack to stack them horizontally.


In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#Vertical Stacking

vertical_stack = np.vstack((A,B))
print(vertical_stack)

#Horizontal Stacking

horizontal_stack = np.hstack((A,B))
print(horizontal_stack)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


14. Scalar operations
- Let X = np.array([10, 20, 30, 40]).
- Subtract 10 from all elements.
- Divide all elements by 10.
- Print the result after each step.


In [17]:
X = np.array([10, 20, 30, 40])

#Subtract 10 from all elements of X

print(X - 10)

#Divide all elements by 10

print(X/10)

[ 0 10 20 30]
[1. 2. 3. 4.]


15. Elementwise operations
Given:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
- Compute a + b
- Compute a * b
- Compute a / b
- Explain why these operations are called elementwise

In [19]:
a = np.array([1, 2, 3])

b = np.array([10, 20, 30])

print(a + b)
print(a * b)
print(a / b)

#These operations are called elementwise since the operation be it +,*,/- etc are applied on all the elements in these arrays.


[11 22 33]
[10 40 90]
[0.1 0.1 0.1]


16. Vector dot product
Given:
w = np.array([1, 2, 3])
x = np.array([4, 5, 6])
- Compute np.dot(w, x).
- Compute w @ x.
- Verify both results are the same.

In [34]:
w = np.array([1, 2, 3])

x = np.array([4, 5, 6])

print(np.dot(w, x))
print(w @ x)

np.dot(w,x) == w @ x


32
32


np.True_

17. Matrix–vector multiplication (simple model)
Given:
X = np.array([
[1, 2, 3],
[4, 5, 6]
])
w = np.array([0.1, 0.2, 0.3])
b = 0.5
- Compute y_pred = X @ w + b.
- What does each element of y_pred represent?

In [22]:
X = np.array([ [1, 2, 3], [4, 5, 6] ])

w = np.array([0.1, 0.2, 0.3])
b = 0.5

# Compute y_pred = X @ w + b.

y_pred = X @ w + b

print(y_pred)

# What does each element of y_pred represent?

#Each element represents a predicted value

[1.9 3.7]


18. Transpose and sums
Given:
A = np.array([[1, 2, 3],
[4, 5, 6]])
- Compute A.T.
- Compute A.sum(axis=0).
- Compute A.sum(axis=1).
- Explain the difference between sum over axis 0 and axis 1.

In [25]:
A = np.array([[1, 2, 3], [4, 5, 6]])

print(A.T)

print(A.sum(axis = 0))

print(A.sum(axis = 1))

[[1 4]
 [2 5]
 [3 6]]
[5 7 9]
[ 6 15]


19. Boolean indexing (filtering)
Given:
prices = np.array([75000, 90000, 120000, 155000, 60000])
- Create a boolean mask for prices > 100000.
- Use it to get only the expensive houses.
- Count how many houses are above 100000.

In [33]:
prices = np.array([75000, 90000, 120000, 155000, 60000])
mask = prices > 100000
print(mask)

expensive_houses = prices[mask]
print(expensive_houses)
print(f"Houses priced above 100000 in this array are {expensive_houses}.")

count_expensive = expensive_houses.size
print(count_expensive)
print(f"There are {count_expensive} premium priced houses in this array")



[False False  True  True False]
[120000 155000]
Houses priced above 100000 in this array are [120000 155000].
2
There are 2 premium priced houses in this array


20. Shuffling dataset (X and y together)
Using the data array from problem 8:
- Split into X (first 3 columns) and y (last column).
- Generate shuffled indices using np.random.permutation(len(X)).
- Create X_shuffled and y_shuffled so that each row and label still match after shuffling.

In [47]:
random_array = np.array([1,2,3,4,5,6])
print(f"Random Array: {random_array}")

print(f"Shuffled Random Array: np.random.permutation(len(random_array))")

arr_2X3 = random_array.reshape(2,3)
print(f"2X3 Matrix: {arr_2X3}")

print(f"Reshuffled Array of the 2X3 Matrices: np.random.permutation(len(arr_2X3)")

Random Array: [1 2 3 4 5 6]
Shuffled Random Array: np.random.permutation(len(random_array))
2X3 Matrix: [[1 2 3]
 [4 5 6]]
Reshuffled Array of the 2X3 Matrices: np.random.permutation(len(arr_2X3)
