<a href="https://colab.research.google.com/github/mehjabeenalam-ux/REC-2-Machine-Learning/blob/main/Class_02_Exercises_DIP_mehjabeen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy is a module or library in Python that deals with fast computation on arrays.

1. Create 1D and 2D arrays
- Create a 1D NumPy array from the Python list [2, 4, 6, 8].
- Create a 2D NumPy array with 2 rows and 3 columns using any numbers you want.

In [41]:
import numpy as np

array_1D = np.array([2,4,6,8])
array_2D = [
          [1,2,3],
          [4,5,6]

]

print(array_1D)
print(type(array_1D))
print(array_2D)
print(type(array_2D))

[2 4 6 8]
<class 'numpy.ndarray'>
[[1, 2, 3], [4, 5, 6]]
<class 'list'>


2. Check basic properties
Given:
X = np.array([[1, 2, 3],
[4, 5, 6]])
- Print X.shape
- Print X.ndim
- Print X.dtype

In [7]:
X = np.array([[1, 2, 3], [4, 5, 6]])
print(X.shape)
print(X.ndim)
print(X.dtype)

(2, 3)
2
int64


3. Zeros and ones
- Create a 3×3 array filled with zeros.
- Create a 2×4 array filled with ones.

In [16]:
#Zeroes
zeroes = np.zeros((3,3))
# print(np.zeros((3,3)))
print(zeroes)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
##Ones
ones = np.ones((2,4))
# print(np.ones((2,4)))
print(ones)

4. arange vs linspace
- Use np.arange to create an array: [0, 2, 4, 6, 8].
- Use np.linspace to create 5 values from 0 to 1 (inclusive).

In [14]:
#np.arrange
array_arange = np.arange(0,9,2)
print(array_arange)

[0 2 4 6 8]


In [15]:
#np.linspace
array_linspace = np.linspace(0, 1, 5)
print(array_linspace)

[0.   0.25 0.5  0.75 1.  ]


5. Indexing single elements
Given:
X = np.array([[800, 2, 15],
[950, 2, 10],
[1200, 3, 8],
[1500, 3, 5]])
- Get the first element (800)
- Get the value 3 (bedrooms of the 3rd row)
- Get the last element (5)

New Array

In [27]:
x_new = np.array([[800, 2, 15],
                  [950, 2, 10],
                  [1200, 3, 8],
                  [1500, 3, 5]]
                 )
print(x_new)

[[ 800    2   15]
 [ 950    2   10]
 [1200    3    8]
 [1500    3    5]]


Get the first element (800)

In [33]:
# print(x[0])
print(x_new[0,0])

800


Get the value 3 (bedrooms of the 3rd row)

In [34]:
print(x_new[2])

[1200    3    8]


Get the last element (5)

In [35]:
print(x_new[3,2])

5


6. Row and column selection
Using the same X as above:
- Get the first row as an array.
- Get the second column (all bedroom values).

Get the first row as an array.

In [42]:
#Get the first row as an array.
print(np.array(x_new[0]))
print(type(np.array(x_new[0])))

[800   2  15]
<class 'numpy.ndarray'>


Get the second column (all bedroom values).

In [65]:
print(np.array(x_new[:,1]))

[2 2 3 3]


7. Slicing rows and columns
From the same X:
- Get the first 2 rows.
- Get rows 1 to 3 and columns 0 to 1.


In [62]:
#Get the first 2 rows.
print(np.array(x_new[0:2]))

[[800   2  15]
 [950   2  10]]


In [63]:
#Get rows 1 to 3 and columns 0 to 1.
print(np.array(x_new[1:4,0:2]))

[[ 950    2]
 [1200    3]
 [1500    3]]


8. Feature/target split
Consider:
data = np.array([
[800, 2, 15, 75000],
[950, 2, 10, 90000],
[1200, 3, 8, 120000],
[1500, 3, 5, 155000]
])
- Use slicing to create X (first 3 columns) and y (last column)

In [72]:
data = np.array([
[800, 2, 15, 75000],
[950, 2, 10, 90000],
[1200, 3, 8, 120000],
[1500, 3, 5, 155000]
])
print(type(data))
print(np.array(data[:,0:3]))
print(np.array(data[:,3]))

<class 'numpy.ndarray'>
[[ 800    2   15]
 [ 950    2   10]
 [1200    3    8]
 [1500    3    5]]
[ 75000  90000 120000 155000]


9. Mean and standard deviation
Using the same data array:
- Compute the overall mean of all numbers.
- Compute the standard deviation of all numbers.


In [82]:
data = np.array([
[800, 2, 15, 75000],
[950, 2, 10, 90000],
[1200, 3, 8, 120000],
[1500, 3, 5, 155000]
])

print(data)
print(type(data))

#Mean
print(np.mean(data))
print(f"Mean of this array is {np.mean(data)}")


#StandardDeviation
# print(np.StandardDeviation(data))

[[   800      2     15  75000]
 [   950      2     10  90000]
 [  1200      3      8 120000]
 [  1500      3      5 155000]]
<class 'numpy.ndarray'>
27781.125
Mean of this array is 27781.125
